spring:
  profiles:
    active: dev
  data:
    redis:
      host: localhost
      port: 6379
      username: sa
      password:
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

---
#application-dev.yml
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa  # 기본 사용자 이름
    password:     # 기본 비밀번호 (비워둠)
    #    url: jdbc:h2:tcp://localhost:9092/~/botox;AUTO_SERVER=TRUE
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: localhost
      port: 6379
      username: sa
      password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type: trace
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG

jwt:
  issuer: kim11
  secretKey: ff54dd1f64544befbeae0e43d1b9df54ff54dd1f64544befbeae0e43d1b9df54ff54dd1f64544befbeae0e43d1b9df54





---
#application-prod.yml
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://botox-rds.clauic2uwfg6.ap-northeast-2.rds.amazonaws.com:3306/botox
    username: admin
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        default_batch_fetch_size: 100
  data:
    redis:
      host: localhost
      port: 6379
      username: sa
      password:

logging:
  file:
    name: /path/to/your/logfile.log
  level:
    org.hibernate.SQL: info
    org.hibernate.type: trace
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    root: INFO
    org.springframework: DEBUG

jwt:
  issuer: kim11
  secretKey: ff54dd1f64544befbeae0e43d1b9df54ff54dd1f64544befbeae0e43d1b9df54ff54dd1f64544befbeae0e43d1b9df54
