spring:
  datasource:
#    url: jdbc:h2:tcp://localhost:9092/~/botox;AUTO_SERVER=TRUE
    url: jdbc:h2:mem:testdb
    username: sa  # 기본 사용자 이름
    password:     # 기본 비밀번호 (비워둠)
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: localhost
      port: 6379
      username: sa
      password:
  jpa:
    hibernate:
      ddl-auto: create